version: '2'
services:
  mysql:
    container_name: h5p_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: Drupal
    ports:
      - "3306"
  web:
    container_name: h5p_web
    build: .
    ports:
      - "80:80"
    volumes:
      - ./development:/var/www/html/sites/default/files/h5p/development
    links:
      - mysql
    depends_on:
      - mysql
